---
- hosts: localhost
  connection: local
  tasks:

  - name: Hello World!
    shell: echo "Hi! Controller is working!"

  - pause:
      minutes: 5

  - debug: msg="{{ '%02d' | format(item) }}"
    loop: "{{ range(1, 6)|list + range(11, 32)|list }}"
...
