---
- hosts: localhost
  connection: local
  tasks:

  - name: Hello World!
    shell: echo "Hi! Controller is working!"

  - name: Show the current custom fact value
    ansible.builtin.debug:
      var: my_custom_fact

  - name: Set cacheable fact
    ansible.builtin.set_fact:
      cacheable: yes
      my_custom_fact: "My custom fact value"

  - pause:
      seconds: 5

  - debug: msg="{{ '%02d' | format(item) }}"
    loop: "{{ range(1, 6)|list + range(11, 32)|list }}"
...
